import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, rmSync } from "fs";
import { resolve } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

if (process.argv[2] === 'clean') {
	rmSync('dist', { recursive: true, force: true });
	process.exit(0);
}

// Ensure dist directory exists
mkdirSync('dist', { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [resolve('src/main.ts')],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: resolve('dist/main.js'),
});

if (prod) {
	await context.rebuild();

	copyFileSync('manifest.json', 'dist/manifest.json');
	console.log('Copied manifest.json to dist/');

	if (existsSync('styles.css')) {
		copyFileSync('styles.css', 'dist/styles.css');
		console.log('Copied styles.css to dist/');
	} else {
		console.log('No styles.css found (optional)');
	}

	console.log('\nProduction build complete. Files ready in dist/ folder');
	process.exit(0);
} else {
	await context.watch();

	copyFileSync('manifest.json', 'dist/manifest.json');
	if (existsSync('styles.css')) {
		copyFileSync('styles.css', 'dist/styles.css');
	}

	console.log("Watching for changes...");
}
