import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Ensure dist directory exists
mkdirSync('dist', { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',  // Output to dist folder
});

if (prod) {
	await context.rebuild();
	
	// Copy manifest and styles to dist
	copyFileSync('manifest.json', 'dist/manifest.json');
	console.log('✓ Copied manifest.json to dist/');
	
	// Copy styles.css if it exists
	try {
		copyFileSync('styles.css', 'dist/styles.css');
		console.log('✓ Copied styles.css to dist/');
	} catch (e) {
		console.log('ℹ No styles.css found (optional)');
	}
	
	console.log('\n✓ Production build complete! Files ready in dist/ folder');
	process.exit(0);
} else {
	await context.watch();
	
	// Copy files for dev mode too
	copyFileSync('manifest.json', 'dist/manifest.json');
	try {
		copyFileSync('styles.css', 'dist/styles.css');
	} catch (e) {
		// styles.css is optional
	}
	
	console.log("👀 Watching for changes...");
}